Wordpress container
digitalocean/container-blueprints pull request #28
Opened 2022-03-25 10:13 UTC by vladciobancai

2022-03-29 15:20 UTC, v-ctiutiu requested changes

2022-03-29 15:20 UTC, v-ctiutiu commented on DOKS-wordpress/README.md
> +**Notes:**
>-  For more details about Nginx Ingress Controller and Cert-Manager, please visit Starter Kit chapter - [How to Configure Ingress using Nginx](https://github.com/digitalocean/Kubernetes-Starter-Kit-Developers/blob/main/03-setup-ingress-controller/nginx.md).
>
>- An alternative way to install [NGINX Ingress Controller](https://marketplace.digitalocean.com/apps/nginx-ingress-controller) and [Cert-Manager](https://marketplace.digitalocean.com/apps/cert-manager) is via the DigitalOcean 1-click apps platform.

2022-03-29 15:20 UTC, v-ctiutiu commented on DOKS-wordpress/README.md
> +Before creating the certificate is required a cluster issuer to be created for cert-mananger in order to know where the certificate to be created, for eg, we will use the Let's Encrypt production. Cr
Maybe something similar to:

>A cluster issuer is required first, in order to obtain the final TLS certificate. Create the following YAML file, and replace <YOUR-EMAIL-HERE> using a valid email address for TLS certificate registration.

2022-03-29 15:20 UTC, v-ctiutiu commented on DOKS-wordpress/README.md
> +### Confiugre plugins
>Configuring WordPress Plugins

2022-03-29 15:20 UTC, v-ctiutiu commented on DOKS-wordpress/README.md
> +### Upgrade WordPress
>Upgrading WordPress

2022-03-29 15:20 UTC, v-ctiutiu commented on DOKS-wordpress/README.md
> +Because of its popularity, WordPress is often a target for malicious exploitation, so it’s important to keep it updated. We can upgrade Helm releases with the command helm upgrade.
>Being so popular, WordPress becomes often a target for malicious exploitation, so it’s important to keep it up to date. You can upgrade WordPress via the `helm upgrade` command.

2022-03-29 15:20 UTC, v-ctiutiu commented on DOKS-wordpress/README.md
> +In this guide, we installed WordPress with an external MySQL server on a Kubernetes cluster using the command-line tool Helm. We also learned how to upgrade a WordPress release to a new chart version
Maybe something similar to:

>In this guide, you learned how to install WordPress the Kubernetes way, using Helm and an external MySQL database. You also learned how to upgrade WordPress to a new version, and how to rollback to a previous release, in case of errors.

2022-03-29 15:20 UTC, v-ctiutiu commented on DOKS-wordpress/README.md
> +[WordPress](https://wordpress.org/about/) is an Open Source software designed for everyone, emphasizing accessibility, performance, security, and ease of use to create a website, blog, or app. [WordP
Maybe something similar to:

>[WordPress](https://wordpress.org/about/) is an open source software designed for everyone, emphasising accessibility, performance, security, and ease of use to create a website, blog, or app.

2022-03-29 15:20 UTC, v-ctiutiu commented on DOKS-wordpress/README.md
> +In this tutorial, we’ll use Helm for setting up [WordPress](https://wordpress.com/) on top of a Kubernetes cluster, in order to create a highly-available website. In addition to leveraging the intrin
Please use "you/you will" instead of "we/we'll". Same applies for every step in the tutorial.

2022-03-29 15:20 UTC, v-ctiutiu commented on DOKS-wordpress/README.md
> +We’ll be using an external MySQL server in order to abstract the database component, since it can be part of a separate cluster or managed service for extended availability. After completing the step
Please use "you/you will" instead of "we/we'll". Same applies for every step in the tutorial.

2022-03-31 12:03 UTC, v-ctiutiu requested changes

2022-03-31 12:03 UTC, v-ctiutiu commented on DOKS-wordpress/README.md
> +Finally, you need to configure on your cluster the Grafana and Prometheus.
Maybe:

>Finally, you need to configure Grafana and Prometheus to visualise metrics exposed by your new WordPress instance.

Shouldn't we add a link here on how to accomplish the above  (maybe pointing to the Starter Kit, or any other DO documentation for that matter) ?

2022-03-31 12:03 UTC, v-ctiutiu commented on DOKS-wordpress/README.md
> +Finally, you need to configure on your cluster the Grafana and Prometheus.
Maybe:

>Finally, the only thing left is to configure Grafana and Prometheus to visualise metrics exposed by your new WordPress instance.

2022-03-31 13:07 UTC, vladciobancai commented on DOKS-wordpress/README.md
>  doctl databases db create 2f0d0969-a8e1-4f94-8b73-2d43c68f8e72  wordpres
Based on this [How to Manage MySQL Users and Databases in a Database Cluster ](https://docs.digitalocean.com/products/databases/mysql/how-to/manage-users-and-databases/) when a user is created receives full permission

2022-04-01 08:38 UTC, v-ctiutiu requested changes

2022-04-01 08:38 UTC, v-ctiutiu commented on DOKS-wordpress/README.md
> +## Table of contents
Don't forget about capitalization:

>Table of Contents

2022-04-01 08:38 UTC, v-ctiutiu commented on DOKS-wordpress/README.md
> +    - [Installing Cert-Manager](#installing-cert-manager)
Please remove redundant new line.

2022-04-01 08:38 UTC, v-ctiutiu commented on DOKS-wordpress/README.md
> +  - [Enabling WordPress Monitoring Metrics](#enabling-wordpress-monitoring-metrics)
Please remove redundant new line.

2022-04-01 08:38 UTC, v-ctiutiu commented on DOKS-wordpress/README.md
> +The new users will receive the full permissions at entire database by default, the privileges can be changed using the following instructions [How to Modify User Privileges in MySQL Databases](https:
Maybe:

> By default, new users get full permissions for the entire database. In general, it's best security practice to restrict new user privileges to the wordpress database only. You can follow the [How to Modify User Privileges in MySQL Databases](https://docs.digitalocean.com/products/databases/mysql/how-to/modify-user-privileges/) guide provided by DigitalOcean to accomplish this task.

2022-04-01 11:11 UTC, v-ctiutiu requested changes

2022-04-01 11:11 UTC, v-ctiutiu commented on DOKS-wordpress/assets/manifests/values.yml
> +wordpressUsername: <WORDPRESS_USER_HERE>
><YOUR_WORDPRESS_USER_NAME_HERE>
><YOUR_WORDPRESS_USER_PASSWORD_HERE>

2022-04-01 11:11 UTC, v-ctiutiu commented on DOKS-wordpress/assets/manifests/values.yml
> +  hostname: <YOUR_DOMAIN_HERE>
What domain more specifically?

Maybe:

><YOUR_WORDPRESS_DOMAIN_HERE>

2022-04-01 11:11 UTC, v-ctiutiu commented on DOKS-wordpress/assets/manifests/values.yml
> +      - <YOUR_DOMAIN_HERE>
What domain more specifically?

Maybe:

><YOUR_WORDPRESS_DOMAIN_HERE>

2022-04-01 11:11 UTC, v-ctiutiu commented on DOKS-wordpress/README.md
> +  hostname: <YOUR_DOMAIN_HERE>
What domain more specifically?

Maybe:

><YOUR_WORDPRESS_DOMAIN_HERE>

2022-04-01 11:11 UTC, v-ctiutiu commented on DOKS-wordpress/README.md
> +      - <YOUR_DOMAIN_HERE>
What domain more specifically?

Maybe:

><YOUR_WORDPRESS_DOMAIN_HERE>

2022-04-01 11:11 UTC, v-ctiutiu commented on DOKS-wordpress/assets/manifests/values.yml
> +externalDatabase:
```
<YOUR_WORDPRESS_MYSQL_DB_HOST_HERE>
<YOUR_WORDPRESS_MYSQL_DB_USER_NAME_HERE>
<YOUR_WORDPRESS_MYSQL_DB_USER_PASSWORD_HERE>
<YOUR_WORDPRESS_MYSQL_DB_NAME_HERE>
```

2022-04-01 11:11 UTC, v-ctiutiu commented on DOKS-wordpress/README.md
> +Replace `WORDPRESS_NEW_VERSION` with the new version.
We can also have a **Known Limitations** section or note, as explained [here](https://artifacthub.io/packages/helm/bitnami/wordpress#known-limitations).

2022-04-04 08:32 UTC, v-ctiutiu requested changes

2022-04-04 08:32 UTC, v-ctiutiu commented on DOKS-wordpress/README.md
> +  user: <MYSQL_DB_USYOUR_WORDPRESS_MYSQL_DB_USER_NAME_HEREER_HERE>
<YOUR_WORDPRESS_MYSQL_DB_USER_NAME_HERE>

2022-04-04 08:39 UTC, v-ctiutiu approved these changes
Looks good to me now.

2022-04-06 21:31 UTC, merged

2022-04-22 11:54 UTC, MattIPv4 commented
Hey, @vladciobancai - Thanks a ton for this sweet PR! 😄

Would you please shoot me an email when you get a chance?
mcowley at digitalocean dot com 🎉